import type { HeroData } from "./types";

export const heroData: HeroData = {
  system: {
    status: "SYS.Online",
    version: "v2.6.1",
    isLive: true,
  },
  eyebrow: {
    left: "Est. 2026",
    right: "Regional",
  },
  title: {
    line1: "Raqamli",
    line2: "maydon.",
    line3: "Haqiqiy",
    line4: "g'alaba.",
  },
  description:
    "O'zbekistondagi eng yirik e-sport platformasi. Turnirlar, jamoalar va o'yinchilar — barchasi bir joyda.",
  ctas: {
    primary: { label: "Turnirlarga qo'shilish", href: "/tournaments" },
    secondary: { label: "Live tomosha", href: "/live" },
  },
  stats: [
    { id: "s1", label: "Faol turnirlar", value: "24" },
    { id: "s2", label: "Jamoalar", value: "186" },
    { id: "s3", label: "O'yinchilar", value: "2,847" },
    { id: "s4", label: "Sovrin", value: "$500K" },
  ],
  breakingNews: [
    {
      id: "n1",
      text: "CYBERARENA 2026 — Regional Final boshlanmoqda",
    },
    {
      id: "n2",
      text: "Team Phantom yangi roster e'lon qildi",
    },
    {
      id: "n3",
      text: "Turnir sovrin jamg'armasi $500,000 ga yetdi",
    },
    {
      id: "n4",
      text: "Yangi o'yin: Valorant Champions qo'shildi",
    },
  ],
  upcomingMatch: {
    teamA: "Phantom",
    teamB: "Vortex",
    time: "21:00",
  },
  ticker: [
    { id: "t1", text: "TURNIR #A1" },
    { id: "t2", text: "REGIONAL FINAL" },
    { id: "t3", text: "PRIZE $500K" },
    { id: "t4", text: "48 JAMOA" },
    { id: "t5", text: "LIVE STREAM" },
    { id: "t6", text: "ASIA PACIFIC" },
    { id: "t7", text: "SEASON 2026" },
  ],
};

// turnement mock data
import type { TournamentsData } from "./types";

export const tournamentsData: TournamentsData = {
  system: {
    status: "SYS.Online",
    version: "v2.6.1",
    isLive: true,
  },
  eyebrow: {
    left: "2026 Season",
    right: "Global",
  },
  heading: {
    line1: "Turnirlar.",
    line2: "Musobaqalar.",
  },
  description:
    "Barcha faol, rejalashtirilgan va yakunlangan turnirlar. Filtrlang, kuzatib boring, qo'shiling.",
  filters: [
    { id: "all", label: "Barchasi", count: 24 },
    { id: "live", label: "Live", count: 3 },
    { id: "upcoming", label: "Rejalashtirilgan", count: 12 },
    { id: "finished", label: "Yakunlangan", count: 9 },
  ],
  tournaments: [
    {
      id: "t1",
      code: "TRN-A1",
      title: "Regional Final",
      game: "CS2",
      status: "live",
      region: "Asia Pacific",
      prize: "$500K",
      teams: 32,
      maxTeams: 32,
      startDate: "2026-06-12T18:00:00Z",
      startLabel: "12 IYN",
      progress: 67,
    },
    {
      id: "t2",
      code: "TRN-A2",
      title: "Champions Series",
      game: "VALORANT",
      status: "live",
      region: "Europe",
      prize: "$250K",
      teams: 24,
      maxTeams: 32,
      startDate: "2026-06-12T20:00:00Z",
      startLabel: "12 IYN",
      progress: 42,
    },
    {
      id: "t3",
      code: "TRN-A3",
      title: "Masters Cup",
      game: "DOTA2",
      status: "live",
      region: "North America",
      prize: "$300K",
      teams: 16,
      maxTeams: 16,
      startDate: "2026-06-12T16:30:00Z",
      startLabel: "12 IYN",
      progress: 88,
    },
    {
      id: "t4",
      code: "TRN-B1",
      title: "Spring Invitational",
      game: "LOL",
      status: "upcoming",
      region: "Korea",
      prize: "$150K",
      teams: 8,
      maxTeams: 16,
      startDate: "2026-06-20T10:00:00Z",
      startLabel: "20 IYN",
      progress: 0,
    },
    {
      id: "t5",
      code: "TRN-B2",
      title: "Pro League Season 8",
      game: "CS2",
      status: "upcoming",
      region: "Global",
      prize: "$750K",
      teams: 12,
      maxTeams: 24,
      startDate: "2026-07-01T14:00:00Z",
      startLabel: "01 IYL",
      progress: 0,
    },
    {
      id: "t6",
      code: "TRN-B3",
      title: "Rising Stars",
      game: "PUBG",
      status: "upcoming",
      region: "Asia",
      prize: "$80K",
      teams: 20,
      maxTeams: 32,
      startDate: "2026-07-15T12:00:00Z",
      startLabel: "15 IYL",
      progress: 0,
    },
    {
      id: "t7",
      code: "TRN-C1",
      title: "Winter Clash 2025",
      game: "VALORANT",
      status: "finished",
      region: "Europe",
      prize: "$200K",
      teams: 16,
      maxTeams: 16,
      startDate: "2025-12-10T18:00:00Z",
      startLabel: "10 DEK",
      progress: 100,
    },
    {
      id: "t8",
      code: "TRN-C2",
      title: "Autumn Open",
      game: "DOTA2",
      status: "finished",
      region: "Asia Pacific",
      prize: "$120K",
      teams: 24,
      maxTeams: 24,
      startDate: "2025-11-05T16:00:00Z",
      startLabel: "05 NOY",
      progress: 100,
    },
  ],
  ticker: [
    { id: "tk1", text: "24 TURNIR" },
    { id: "tk2", text: "3 LIVE" },
    { id: "tk3", text: "12 REJALASHTIRILGAN" },
    { id: "tk4", text: "9 YAKUNLANGAN" },
    { id: "tk5", text: "$2.35M SOVRIN" },
    { id: "tk6", text: "SEASON 2026" },
  ],
};
