import type {
  HeroData,
  PlayersData,
  TeamsData,
  TournamentsData,
} from "./types";

export const heroData: HeroData = {
  system: {
    status: "SYS.Online",
    version: "v2.6.1",
    isLive: true,
  },
  eyebrow: {
    left: "Est. 2026",
    right: "Regional",
  },
  title: {
    line1: "Raqamli",
    line2: "maydon.",
    line3: "Haqiqiy",
    line4: "g'alaba.",
  },
  description:
    "O'zbekistondagi eng yirik e-sport platformasi. Turnirlar, jamoalar va o'yinchilar — barchasi bir joyda.",
  ctas: {
    primary: { label: "Turnirlarga qo'shilish", href: "/tournaments" },
    secondary: { label: "Live tomosha", href: "/live" },
  },
  stats: [
    { id: "s1", label: "Faol turnirlar", value: "24" },
    { id: "s2", label: "Jamoalar", value: "186" },
    { id: "s3", label: "O'yinchilar", value: "2,847" },
    { id: "s4", label: "Sovrin", value: "$500K" },
  ],
  breakingNews: [
    {
      id: "n1",
      text: "CYBERARENA 2026 — Regional Final boshlanmoqda",
    },
    {
      id: "n2",
      text: "Team Phantom yangi roster e'lon qildi",
    },
    {
      id: "n3",
      text: "Turnir sovrin jamg'armasi $500,000 ga yetdi",
    },
    {
      id: "n4",
      text: "Yangi o'yin: Valorant Champions qo'shildi",
    },
  ],
  upcomingMatch: {
    teamA: "Phantom",
    teamB: "Vortex",
    time: "21:00",
  },
  ticker: [
    { id: "t1", text: "TURNIR #A1" },
    { id: "t2", text: "REGIONAL FINAL" },
    { id: "t3", text: "PRIZE $500K" },
    { id: "t4", text: "48 JAMOA" },
    { id: "t5", text: "LIVE STREAM" },
    { id: "t6", text: "ASIA PACIFIC" },
    { id: "t7", text: "SEASON 2026" },
  ],
};

// turnement mock data

export const tournamentsData: TournamentsData = {
  system: {
    status: "SYS.Online",
    version: "v2.6.1",
    isLive: true,
  },
  eyebrow: {
    left: "2026 Season",
    right: "Global",
  },
  heading: {
    line1: "Turnirlar.",
    line2: "Musobaqalar.",
  },
  description:
    "Barcha faol, rejalashtirilgan va yakunlangan turnirlar. Filtrlang, kuzatib boring, qo'shiling.",
  filters: [
    { id: "all", label: "Barchasi", count: 24 },
    { id: "live", label: "Live", count: 3 },
    { id: "upcoming", label: "Rejalashtirilgan", count: 12 },
    { id: "finished", label: "Yakunlangan", count: 9 },
  ],
  tournaments: [
    {
      id: "t1",
      code: "TRN-A1",
      title: "Regional Final",
      game: "CS2",
      status: "live",
      region: "Asia Pacific",
      prize: "$500K",
      teams: 32,
      maxTeams: 32,
      startDate: "2026-06-12T18:00:00Z",
      startLabel: "12 IYN",
      progress: 67,
    },
    {
      id: "t2",
      code: "TRN-A2",
      title: "Champions Series",
      game: "VALORANT",
      status: "live",
      region: "Europe",
      prize: "$250K",
      teams: 24,
      maxTeams: 32,
      startDate: "2026-06-12T20:00:00Z",
      startLabel: "12 IYN",
      progress: 42,
    },
    {
      id: "t3",
      code: "TRN-A3",
      title: "Masters Cup",
      game: "DOTA2",
      status: "live",
      region: "North America",
      prize: "$300K",
      teams: 16,
      maxTeams: 16,
      startDate: "2026-06-12T16:30:00Z",
      startLabel: "12 IYN",
      progress: 88,
    },
    {
      id: "t4",
      code: "TRN-B1",
      title: "Spring Invitational",
      game: "LOL",
      status: "upcoming",
      region: "Korea",
      prize: "$150K",
      teams: 8,
      maxTeams: 16,
      startDate: "2026-06-20T10:00:00Z",
      startLabel: "20 IYN",
      progress: 0,
    },
    {
      id: "t5",
      code: "TRN-B2",
      title: "Pro League Season 8",
      game: "CS2",
      status: "upcoming",
      region: "Global",
      prize: "$750K",
      teams: 12,
      maxTeams: 24,
      startDate: "2026-07-01T14:00:00Z",
      startLabel: "01 IYL",
      progress: 0,
    },
    {
      id: "t6",
      code: "TRN-B3",
      title: "Rising Stars",
      game: "PUBG",
      status: "upcoming",
      region: "Asia",
      prize: "$80K",
      teams: 20,
      maxTeams: 32,
      startDate: "2026-07-15T12:00:00Z",
      startLabel: "15 IYL",
      progress: 0,
    },
    {
      id: "t7",
      code: "TRN-C1",
      title: "Winter Clash 2025",
      game: "VALORANT",
      status: "finished",
      region: "Europe",
      prize: "$200K",
      teams: 16,
      maxTeams: 16,
      startDate: "2025-12-10T18:00:00Z",
      startLabel: "10 DEK",
      progress: 100,
    },
    {
      id: "t8",
      code: "TRN-C2",
      title: "Autumn Open",
      game: "DOTA2",
      status: "finished",
      region: "Asia Pacific",
      prize: "$120K",
      teams: 24,
      maxTeams: 24,
      startDate: "2025-11-05T16:00:00Z",
      startLabel: "05 NOY",
      progress: 100,
    },
  ],
  ticker: [
    { id: "tk1", text: "24 TURNIR" },
    { id: "tk2", text: "3 LIVE" },
    { id: "tk3", text: "12 REJALASHTIRILGAN" },
    { id: "tk4", text: "9 YAKUNLANGAN" },
    { id: "tk5", text: "$2.35M SOVRIN" },
    { id: "tk6", text: "SEASON 2026" },
  ],
};

// Team mock data

export const teamsData: TeamsData = {
  system: {
    status: "SYS.Online",
    version: "v2.6.1",
    isLive: true,
  },
  eyebrow: {
    left: "2026 Season",
    right: "Global Roster",
  },
  heading: {
    line1: "Jamoalar.",
    line2: "Rosterlar.",
  },
  description:
    "Platformadagi barcha faol jamoalar. Reyting, tarkib va statistika — barchasi bir joyda.",
  filters: [
    { id: "all", label: "Barchasi", count: 186 },
    { id: "active", label: "Faol", count: 142 },
    { id: "recruiting", label: "O'yinchi qidirmoqda", count: 31 },
    { id: "inactive", label: "Nofaol", count: 13 },
  ],
  teams: [
    {
      id: "tm1",
      code: "TM-001",
      name: "Phantom",
      tag: "PHM",
      game: "CS2",
      status: "active",
      region: "Asia Pacific",
      country: "UZ",
      rank: 1,
      points: 2847,
      winRate: 78,
      wins: 42,
      losses: 12,
      captain: "kaze",
      founded: "2021",
      members: [
        { id: "m1", nickname: "kaze", role: "IGL", country: "UZ" },
        { id: "m2", nickname: "frost", role: "AWP", country: "KZ" },
        { id: "m3", nickname: "nova", role: "Entry", country: "UZ" },
        { id: "m4", nickname: "arc", role: "Support", country: "TR" },
        { id: "m5", nickname: "vex", role: "Lurk", country: "UZ" },
      ],
    },
    {
      id: "tm2",
      code: "TM-002",
      name: "Vortex",
      tag: "VTX",
      game: "VALORANT",
      status: "active",
      region: "Europe",
      country: "SE",
      rank: 2,
      points: 2612,
      winRate: 71,
      wins: 38,
      losses: 15,
      captain: "lynx",
      founded: "2020",
      members: [
        { id: "m6", nickname: "lynx", role: "Duelist", country: "SE" },
        { id: "m7", nickname: "echo", role: "Controller", country: "DE" },
        { id: "m8", nickname: "sage", role: "Sentinel", country: "FI" },
        { id: "m9", nickname: "rift", role: "Initiator", country: "NO" },
        { id: "m10", nickname: "kilo", role: "Flex", country: "SE" },
      ],
    },
    {
      id: "tm3",
      code: "TM-003",
      name: "Nebula",
      tag: "NBL",
      game: "DOTA2",
      status: "active",
      region: "North America",
      country: "US",
      rank: 3,
      points: 2489,
      winRate: 68,
      wins: 34,
      losses: 16,
      captain: "orion",
      founded: "2019",
      members: [
        { id: "m11", nickname: "orion", role: "Carry", country: "US" },
        { id: "m12", nickname: "vega", role: "Mid", country: "CA" },
        { id: "m13", nickname: "atlas", role: "Offlane", country: "US" },
        { id: "m14", nickname: "rune", role: "Support", country: "BR" },
        { id: "m15", nickname: "glint", role: "Hard Support", country: "US" },
      ],
    },
    {
      id: "tm4",
      code: "TM-004",
      name: "Cipher",
      tag: "CPH",
      game: "LOL",
      status: "recruiting",
      region: "Korea",
      country: "KR",
      rank: 8,
      points: 1923,
      winRate: 62,
      wins: 26,
      losses: 16,
      captain: "hanul",
      founded: "2022",
      members: [
        { id: "m16", nickname: "hanul", role: "Top", country: "KR" },
        { id: "m17", nickname: "jun", role: "Jungle", country: "KR" },
        { id: "m18", nickname: "sol", role: "Mid", country: "KR" },
      ],
    },
    {
      id: "tm5",
      code: "TM-005",
      name: "Rift",
      tag: "RFT",
      game: "CS2",
      status: "recruiting",
      region: "Asia",
      country: "UZ",
      rank: 12,
      points: 1687,
      winRate: 58,
      wins: 21,
      losses: 15,
      captain: "sable",
      founded: "2023",
      members: [
        { id: "m19", nickname: "sable", role: "IGL", country: "UZ" },
        { id: "m20", nickname: "onyx", role: "AWP", country: "UZ" },
        { id: "m21", nickname: "wraith", role: "Entry", country: "KG" },
        { id: "m22", nickname: "ember", role: "Support", country: "UZ" },
      ],
    },
    {
      id: "tm6",
      code: "TM-006",
      name: "Aurora",
      tag: "AUR",
      game: "PUBG",
      status: "active",
      region: "Europe",
      country: "PL",
      rank: 15,
      points: 1542,
      winRate: 55,
      wins: 19,
      losses: 15,
      captain: "borealis",
      founded: "2021",
      members: [
        { id: "m23", nickname: "borealis", role: "IGL", country: "PL" },
        { id: "m24", nickname: "polar", role: "Fragger", country: "PL" },
        { id: "m25", nickname: "glacier", role: "Support", country: "CZ" },
        { id: "m26", nickname: "aurum", role: "Scout", country: "SK" },
      ],
    },
    {
      id: "tm7",
      code: "TM-007",
      name: "Obsidian",
      tag: "OBS",
      game: "VALORANT",
      status: "inactive",
      region: "Asia Pacific",
      country: "JP",
      rank: 24,
      points: 1128,
      winRate: 48,
      wins: 14,
      losses: 15,
      captain: "kuro",
      founded: "2020",
      members: [
        { id: "m27", nickname: "kuro", role: "Duelist", country: "JP" },
        { id: "m28", nickname: "shiro", role: "Controller", country: "JP" },
        { id: "m29", nickname: "rei", role: "Sentinel", country: "JP" },
      ],
    },
    {
      id: "tm8",
      code: "TM-008",
      name: "Zenith",
      tag: "ZNT",
      game: "DOTA2",
      status: "active",
      region: "South America",
      country: "BR",
      rank: 6,
      points: 2145,
      winRate: 65,
      wins: 30,
      losses: 16,
      captain: "titan",
      founded: "2019",
      members: [
        { id: "m30", nickname: "titan", role: "Carry", country: "BR" },
        { id: "m31", nickname: "apex", role: "Mid", country: "AR" },
        { id: "m32", nickname: "core", role: "Offlane", country: "BR" },
        { id: "m33", nickname: "flux", role: "Support", country: "CL" },
        { id: "m34", nickname: "helix", role: "Hard Support", country: "BR" },
      ],
    },
  ],
  ticker: [
    { id: "tk1", text: "186 JAMOA" },
    { id: "tk2", text: "142 FAOL" },
    { id: "tk3", text: "31 O'YINCHI QIDIRMOQDA" },
    { id: "tk4", text: "2,847 O'YINCHI" },
    { id: "tk5", text: "GLOBAL RANKING" },
    { id: "tk6", text: "SEASON 2026" },
  ],
};

export const playersData: PlayersData = {
  system: {
    status: "SYS.Online",
    version: "v2.6.1",
    isLive: true,
  },
  eyebrow: {
    left: "2026 Season",
    right: "Global Ranking",
  },
  heading: {
    line1: "O'yinchilar.",
    line2: "Reytinglar.",
  },
  description:
    "Platformadagi eng yaxshi o'yinchilar. Reyting, statistika va karyera — barchasi bir joyda.",
  filters: [
    { id: "all", label: "Barchasi", count: 2847 },
    { id: "signed", label: "Jamoalarda", count: 2104 },
    { id: "free-agent", label: "Erkin agentlar", count: 728 },
    { id: "retired", label: "Faoliyatni yakunlagan", count: 15 },
  ],
  players: [
    {
      id: "pl1",
      code: "PL-0001",
      nickname: "kaze",
      realName: "Aziz Karimov",
      country: "UZ",
      age: 22,
      role: "IGL",
      game: "CS2",
      status: "signed",
      teamId: "tm1",
      teamName: "Phantom",
      teamTag: "PHM",
      rank: 1,
      rating: 94,
      kd: 1.42,
      winRate: 78,
      matches: 542,
      earnings: "$285K",
      joinedAt: "2021",
      streak: 7,
    },
    {
      id: "pl2",
      code: "PL-0002",
      nickname: "lynx",
      realName: "Erik Lindqvist",
      country: "SE",
      age: 24,
      role: "Duelist",
      game: "VALORANT",
      status: "signed",
      teamId: "tm2",
      teamName: "Vortex",
      teamTag: "VTX",
      rank: 2,
      rating: 92,
      kd: 1.36,
      winRate: 71,
      matches: 487,
      earnings: "$220K",
      joinedAt: "2020",
      streak: 4,
    },
    {
      id: "pl3",
      code: "PL-0003",
      nickname: "orion",
      realName: "Marcus Chen",
      country: "US",
      age: 26,
      role: "Carry",
      game: "DOTA2",
      status: "signed",
      teamId: "tm3",
      teamName: "Nebula",
      teamTag: "NBL",
      rank: 3,
      rating: 91,
      kd: 1.29,
      winRate: 68,
      matches: 623,
      earnings: "$198K",
      joinedAt: "2019",
      streak: 3,
    },
    {
      id: "pl4",
      code: "PL-0004",
      nickname: "frost",
      realName: "Nurlan Bekov",
      country: "KZ",
      age: 21,
      role: "AWP",
      game: "CS2",
      status: "signed",
      teamId: "tm1",
      teamName: "Phantom",
      teamTag: "PHM",
      rank: 4,
      rating: 90,
      kd: 1.51,
      winRate: 78,
      matches: 412,
      earnings: "$176K",
      joinedAt: "2022",
      streak: 7,
    },
    {
      id: "pl5",
      code: "PL-0005",
      nickname: "titan",
      realName: "Rafael Silva",
      country: "BR",
      age: 25,
      role: "Carry",
      game: "DOTA2",
      status: "signed",
      teamId: "tm8",
      teamName: "Zenith",
      teamTag: "ZNT",
      rank: 5,
      rating: 89,
      kd: 1.24,
      winRate: 65,
      matches: 578,
      earnings: "$164K",
      joinedAt: "2019",
      streak: 2,
    },
    {
      id: "pl6",
      code: "PL-0006",
      nickname: "nova",
      realName: "Sardor Yusupov",
      country: "UZ",
      age: 19,
      role: "Entry",
      game: "CS2",
      status: "signed",
      teamId: "tm1",
      teamName: "Phantom",
      teamTag: "PHM",
      rank: 6,
      rating: 88,
      kd: 1.18,
      winRate: 78,
      matches: 287,
      earnings: "$98K",
      joinedAt: "2023",
      streak: 7,
    },
    {
      id: "pl7",
      code: "PL-0007",
      nickname: "sable",
      realName: "Jasur Rahimov",
      country: "UZ",
      age: 23,
      role: "IGL",
      game: "CS2",
      status: "signed",
      teamId: "tm5",
      teamName: "Rift",
      teamTag: "RFT",
      rank: 7,
      rating: 87,
      kd: 1.15,
      winRate: 58,
      matches: 342,
      earnings: "$72K",
      joinedAt: "2023",
      streak: -2,
    },
    {
      id: "pl8",
      code: "PL-0008",
      nickname: "vega",
      realName: "Chloe Martin",
      country: "CA",
      age: 27,
      role: "Mid",
      game: "DOTA2",
      status: "signed",
      teamId: "tm3",
      teamName: "Nebula",
      teamTag: "NBL",
      rank: 8,
      rating: 86,
      kd: 1.21,
      winRate: 68,
      matches: 512,
      earnings: "$142K",
      joinedAt: "2019",
      streak: 3,
    },
    {
      id: "pl9",
      code: "PL-0009",
      nickname: "hanul",
      realName: "Kim Hanul",
      country: "KR",
      age: 20,
      role: "Mid",
      game: "LOL",
      status: "signed",
      teamId: "tm4",
      teamName: "Cipher",
      teamTag: "CPH",
      rank: 9,
      rating: 85,
      kd: 1.32,
      winRate: 62,
      matches: 265,
      earnings: "$84K",
      joinedAt: "2022",
      streak: -1,
    },
    {
      id: "pl10",
      code: "PL-0010",
      nickname: "vex",
      realName: "Bekzod Aliyev",
      country: "UZ",
      age: 20,
      role: "Lurk",
      game: "CS2",
      status: "free-agent",
      teamId: null,
      teamName: null,
      teamTag: null,
      rank: 24,
      rating: 79,
      kd: 1.08,
      winRate: 54,
      matches: 198,
      earnings: "$32K",
      joinedAt: "—",
      streak: 0,
    },
    {
      id: "pl11",
      code: "PL-0011",
      nickname: "wraith",
      realName: "Temur Ismoilov",
      country: "UZ",
      age: 22,
      role: "Entry",
      game: "CS2",
      status: "free-agent",
      teamId: null,
      teamName: null,
      teamTag: null,
      rank: 31,
      rating: 77,
      kd: 1.05,
      winRate: 52,
      matches: 176,
      earnings: "$28K",
      joinedAt: "—",
      streak: 1,
    },
    {
      id: "pl12",
      code: "PL-0012",
      nickname: "kuro",
      realName: "Tanaka Kuro",
      country: "JP",
      age: 28,
      role: "Duelist",
      game: "VALORANT",
      status: "retired",
      teamId: null,
      teamName: null,
      teamTag: null,
      rank: 142,
      rating: 72,
      kd: 0.98,
      winRate: 48,
      matches: 612,
      earnings: "$156K",
      joinedAt: "2018",
      streak: 0,
    },
  ],
  ticker: [
    { id: "tk1", text: "2,847 O'YINCHI" },
    { id: "tk2", text: "2,104 JAMOADA" },
    { id: "tk3", text: "728 ERKIN AGENT" },
    { id: "tk4", text: "GLOBAL RANKING" },
    { id: "tk5", text: "$2.35M SOVRIN" },
    { id: "tk6", text: "SEASON 2026" },
  ],
};
